### ISSUE TITLE
Package cannot access server

### ISSUE THREAD

**Issue by nschmelzle** [leftshift/python_mvg_api#10]
I tried the package today. Unfortunately Server returns:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>451 Unavailable For Legal Reasons</title>
</head><body>
<h1>Forbidden</h1>
<p>We can not allow access to /fahrinfo/api/location/queryWeb?q=hauptbahnhof</p><p>Check out <a href="https://www.bayern-fahrplan.de/">Bayern Fahrplan</a></p>
</body></html> 
```

**Comment by nschmelzle** [comment]
Apparently the header of the get request ([in this line](https://github.com/leftshift/python_mvg_api/blob/107d37207f9840bcec2d4a30744b7430cae1cf29/mvg_api/__init__.py#L18)) just needs a User-Agent field.
Like this one from the [MMM-mvgmunich](https://github.com/mrVragec/MMM-mvgmunich/blob/1c34fc740f0b4e4de3be22fec1aa2449a4fce4d3/node_helper.js#L14) project:
```
"User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.110 Safari/537.36"
```

**Comment by NPG75** [comment]
Perfect, thanks a million had same issue now appears to be operational again.

**Comment by leftshift** [comment]
Sorry for the wait, I'll push a new release in a bit :)
