### ISSUE TITLE
Filter Function

### ISSUE THREAD

**Issue by JThyroff** [leftshift/python_mvg_api#22]
Hi,
I would like to use your API for a simple Widget and wondered whether there is a filter function provided to filter the route results by product / type to make the JSON processing easier. Maybe this would be a nice way to improve the API.
Keep on the good work!

**Comment by leftshift** [comment]
Hi,
thanks for your input, I can definitely see how this can be useful but I'm a bit unsure whether I would like it to be part of the library. Right now, the library doesn't make a lot of assertions about the contents of the api responses as it proved to be quite unstable in the past.

However, I'd definitely like having a few recepies for things like this in the documentation.
For example, you can filter by product like this:
```
filter(lambda d: d['product'] == 'UBAHN', mvg_api.get_departures(1))
```
