### ISSUE TITLE
RequestsJSONDecodeError

### ISSUE THREAD

**Issue by kotaston** [leftshift/python_mvg_api#31]
Hello,

thanks for the great api, unfortunately it seems to have stopped working within the last days/weeks. Every request raises the following Error:
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
The Response from the request seems to be in an invalid format, not allowing the api to process the information. As I was currently using the api for my bachelors thesis I would be very grateful for any information, fixes or updates on the matter.

**Comment by lion1505** [comment]
I couldn't reach the API for at least 3 weeks now. 
I would also be very grateful for any information since I'm using it for my mobile app...

**Comment by leftshift** [comment]
This seems to finally be the end for this project, the API endpoint it was using is returning a 404 response now. It had previously been unavailable for a bit but seems to have come back in the meantime: #29

I recommend switching to https://github.com/mondbaron/mvg, which uses a newer API endpoint and also supports async usage.

I'll add a note about this to the readme and archive this project to avoid other people running into this same problem. Thanks for reporting!
