### ISSUE TITLE
License

### ISSUE THREAD

**Issue by robinjanke** [leftshift/python_mvg_api#9]
I would like to write a app that uses this api but i am not sure about the license to use this api. Do you have any contact with the mvg where they allow or deny to use this api for public projects?

**Comment by leftshift** [comment]
Hi. As far as I'm aware, they neither publicly allow nor deny usage of the API. I have not been in direct contact with them about this.

**Comment by mayrstefan** [comment]
From https://www.mvg.de/impressum.html

> Unsere Systeme dienen der direkten Kundeninteraktion. Die Verarbeitung unserer Inhalte oder Daten durch Dritte erfordert unsere ausdrückliche Zustimmung. Für private, nicht-kommerzielle Zwecke, wird eine gemäßigte Nutzung ohne unsere ausdrückliche Zustimmung geduldet. Jegliche Form von Data-Mining stellt keine gemäßigte Nutzung dar. Wir behalten uns vor, die Duldung grundsätzlich oder in Einzelfällen zu widerrufen.

I would say this is some kind of private fair use policy

**Comment by leftshift** [comment]
Thanks for making me aware of this! Yeah, I think that probably covers most use cases of people using this library. I'll add a note to the readme.
